import type { NextPage } from 'next'
import Head from 'next/head'
import MDEditor from '../components/MDEditor'
import Menu from '../components/Menu'
import MenuNav from '../components/MenuNav'
import SFooter from '../components/SFooter'
import styles from '../styles/Home.module.css'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next dApp</title>
        <meta name="description" content="Generated by create next dapp" />
        <link rel="icon" href="/max_logo.svg" />
      </Head>
      {/* <Header /> */}
      <main className={styles.main}>
        <article className={styles.paralaxStyle} id='art01'><MDEditor /></article>
        <article className={styles.greenStyle}   id='art02'>Article Two</article>
        <article className={styles.paralaxStyle} id='art03'>Article Three</article>
        <article className={styles.whiteStyle}   id='art04'>Article Four</article>
        <article className={styles.paralaxStyle} id='art05'>Article Five</article>
        <article className={styles.redStyle}     id='art06'>Article Six</article>
        <article className={styles.paralaxStyle} id='art07'>Article Seven</article>
      </main>
      <Menu></Menu>
      <MenuNav></MenuNav>
      <SFooter></SFooter>
      <video className={styles.background_video} loop muted autoPlay  
        poster="https://simpledoers.eth.limo/max_logo.svg">
        <source src="https://simpledoers.eth.limo/video_bg.mp4"   
                type="video/mp4" />
      </video>
      <script src="https://cdn.jsdelivr.net/npm/ipfs/dist/index.min.js"></script>
    </div>
  )
}
export default Home
